# Generated by Django 3.0.3 on 2020-02-17 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('result', models.IntegerField(null=True)),
                ('state', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('analyzed_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
