# Generated by Django 3.0.3 on 2020-02-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='result',
            field=models.BigIntegerField(null=True),
        ),
    ]
